"""
Financial Analyst LLM Agent Orchestrator for Arthra MCP.
Orchestrates tool calls (data ingestion, technicals, fundamentals, mutual funds, Plotly charts)
and synthesizes comprehensive Markdown Financial Reports.
"""

from typing import Dict, Any, List, Optional
import os
import datetime
import logging
from src.mcp_server.tools import (
    tool_search_indian_symbol,
    tool_fetch_financial_data,
    tool_analyze_and_visualize,
    tool_compare_assets,
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

REPORTS_DIR = os.path.abspath("reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


class FinancialAnalystAgent:
    """
    Intelligent Financial Analyst Agent using MCP tools to query, compute, and visualize Indian market assets.
    """

    def __init__(self, name: str = "Arthra Financial Analyst"):
        self.name = name

    def analyze_stock(self, symbol: str, period: str = "1y") -> Dict[str, Any]:
        """
        Executes complete stock analysis workflow: quote, fundamentals, technicals, and Plotly chart.
        """
        logger.info(f"[{self.name}] Analyzing Indian Equity Stock: '{symbol}' ({period})")
        res = tool_analyze_and_visualize(symbol, asset_type="stock", period=period, generate_chart=True)
        
        company_name = res.get("companyName", symbol)
        norm_symbol = res.get("symbol", symbol)
        tech = res.get("technicalAnalysis", {})
        fund = res.get("fundamentalScorecard", {})
        chart_path = res.get("chartPath")
        chart_url = res.get("chartUrl")

        # Synthesize Markdown Report
        now_str = datetime.datetime.now().strftime("%d %B %Y, %H:%M IST")
        
        report_md = f"""# 📊 Financial Research Report: {company_name} ({norm_symbol})
> **Generated by {self.name}** | Date: {now_str} | Benchmark: NIFTY 50 (`^NSEI`)

---

## 🎯 Executive Summary & Investment Rating

| Metric | Rating / Value | Description |
| :--- | :--- | :--- |
| **Technical Sentiment** | **{tech.get('sentiment', 'NEUTRAL')}** | Price vs SMA 20/50/200 & MACD Crossovers |
| **Financial Health Score** | **{fund.get('healthScore', 0)} / 100** | {fund.get('scoreRating', 'N/A')} |
| **Valuation Rating** | **{fund.get('valuationStatus', 'N/A')}** | P/E: {fund.get('trailingPE', 'N/A')} \| P/B: {fund.get('priceToBook', 'N/A')} |
| **Volatility / Risk** | **{tech.get('volatility', 0)}% Ann. Vol** | Beta vs NIFTY 50: {tech.get('beta', 1.0)} |

---

## 🧮 100-Point Financial Health Scorecard

- **Overall Score**: `{fund.get('healthScore', 0)} / 100` — **{fund.get('scoreRating', 'N/A')}**
- **Valuation Assessment**: `{fund.get('valuationStatus', 'N/A')}`

### Scorecard Breakdown:
"""
        for bd in (fund.get("scoreBreakdown") or []):
            report_md += f"- • {bd}\n"

        report_md += f"""
---

## 📈 Technical Indicators & Market Signals

- **Latest Closing Price**: `₹{tech.get('latestClose', 'N/A')}`
- **RSI (14)**: `{tech.get('rsi', 'N/A')}`
- **Simple Moving Averages**:
  - 20-Day SMA: `₹{tech.get('sma20', 'N/A')}`
  - 50-Day SMA: `₹{tech.get('sma50', 'N/A')}`
  - 200-Day SMA: `₹{tech.get('sma200', 'N/A')}`
- **MACD**: `Line: {tech.get('macd', 'N/A')}`

### Key Technical Signals:
"""
        for sig in (tech.get("signalHighlights") or []):
            report_md += f"- • {sig}\n"

        if chart_url:
            report_md += f"""
---

## 📊 Interactive Visualization

- **Interactive Candlestick & Technical Chart**: [{norm_symbol}_technical.html]({chart_url})
*(Open the HTML link in your web browser to interact with zoom, pan, and hover tooltips).*
"""

        clean_file = norm_symbol.replace(".", "_")
        filepath = os.path.join(REPORTS_DIR, f"{clean_file}_report.md")
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_md)

        logger.info(f"Saved Markdown report to: {filepath}")
        return {
            "symbol": norm_symbol,
            "companyName": company_name,
            "analysis": res,
            "reportPath": filepath,
            "reportMarkdown": report_md
        }

    def analyze_mutual_fund(self, scheme_code_or_query: str) -> Dict[str, Any]:
        """
        Executes complete mutual fund analysis workflow: scheme metadata, CAGR, Sharpe, Drawdown, and Plotly chart.
        """
        logger.info(f"[{self.name}] Analyzing Indian Mutual Fund: '{scheme_code_or_query}'")
        
        # If query string -> resolve scheme code
        scheme_code = scheme_code_or_query
        if not str(scheme_code_or_query).isdigit():
            search_res = tool_search_indian_symbol(scheme_code_or_query)
            matches = search_res.get("mutualFundMatches", [])
            if matches:
                scheme_code = matches[0]["schemeCode"]
            else:
                raise ValueError(f"No mutual fund scheme matching '{scheme_code_or_query}' found.")

        res = tool_analyze_and_visualize(str(scheme_code), asset_type="mutual_fund", generate_chart=True)
        
        scheme_name = res.get("schemeName", f"Scheme {scheme_code}")
        fund_house = res.get("fundHouse", "N/A")
        category = res.get("category", "N/A")
        quant = res.get("quantitativeAnalysis", {})
        chart_url = res.get("chartUrl")
        mdd = quant.get("maxDrawdown", {})
        rolling = quant.get("rollingReturns1Y", {})

        now_str = datetime.datetime.now().strftime("%d %B %Y, %H:%M IST")

        report_md = f"""# 🏦 Mutual Fund Performance Report: {scheme_name}
> **Generated by {self.name}** | Date: {now_str} | AMFI Scheme Code: `{scheme_code}`

---

## 🎯 Executive Summary & Scheme Overview

| Field | Value |
| :--- | :--- |
| **Scheme Name** | **{scheme_name}** |
| **Fund House** | {fund_house} |
| **Category** | {category} |
| **Latest NAV** | **₹{quant.get('latestNav', 'N/A')}** (as of {quant.get('endDate', 'N/A')}) |
| **Track Record** | {quant.get('totalYearsHistory', 'N/A')} Years ({quant.get('startDate', 'N/A')} to {quant.get('endDate', 'N/A')}) |

---

## 📈 Risk-Adjusted Returns & CAGR

| Metric | Return (%) / Ratio | Description |
| :--- | :--- | :--- |
| **1-Year CAGR** | `{quant.get('cagr1Y', 'N/A')}%` | Past 1 Year Return |
| **3-Year CAGR** | `{quant.get('cagr3Y', 'N/A')}%` | Past 3 Years Annualized Return |
| **5-Year CAGR** | `{quant.get('cagr5Y', 'N/A')}%` | Past 5 Years Annualized Return |
| **CAGR Since Inception** | **`{quant.get('cagrInception', 'N/A')}%`** | Return since fund launch |
| **Sharpe Ratio** | **`{quant.get('sharpeRatio', 'N/A')}`** | vs RBI 6.5% T-Bill benchmark |
| **Sortino Ratio** | `{quant.get('sortinoRatio', 'N/A')}` | Downside risk-adjusted return |
| **Annualized Volatility** | `{quant.get('annualizedVolatility', 'N/A')}%` | Standard deviation of daily returns |

---

## 📉 Drawdown & 1-Year Rolling Returns

- **Maximum Drawdown**: **`-{mdd.get('maxDrawdownPercent', 'N/A')}%`** (Peak: {mdd.get('peakDate', 'N/A')} → Trough: {mdd.get('troughDate', 'N/A')})
- **1-Year Rolling Returns Summary**:
  - **Average Rolling Return**: `{rolling.get('averageRollingReturn', 'N/A')}%`
  - **Minimum Rolling Return**: `{rolling.get('minRollingReturn', 'N/A')}%`
  - **Maximum Rolling Return**: `{rolling.get('maxRollingReturn', 'N/A')}%`
  - **Positive Return Years**: `{rolling.get('positivePercentage', 'N/A')}%`
"""

        if chart_url:
            report_md += f"""
---

## 📊 Interactive Visualization

- **Interactive NAV Trajectory & Drawdown Chart**: [MF_{scheme_code}_performance.html]({chart_url})
*(Open the HTML link in your web browser to interact with zoom, pan, and hover tooltips).*
"""

        filepath = os.path.join(REPORTS_DIR, f"MF_{scheme_code}_report.md")
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_md)

        logger.info(f"Saved Mutual Fund report to: {filepath}")
        return {
            "schemeCode": scheme_code,
            "schemeName": scheme_name,
            "analysis": res,
            "reportPath": filepath,
            "reportMarkdown": report_md
        }

    def process_natural_language_query(self, query: str) -> Dict[str, Any]:
        """
        Parses natural language query, determines intent (Stock vs Mutual Fund vs Search), and executes analysis.
        """
        logger.info(f"[{self.name}] Processing Natural Language Query: '{query}'")
        import re
        q_lower = query.lower().strip()
        
        # Check if query is about Mutual Fund
        if "mutual fund" in q_lower or "mf" in q_lower or "fund" in q_lower or q_lower.isdigit():
            clean_q = re.sub(r'(?i)\b(analyze|mutual fund|fund|mf|share|stock)\b', '', query).strip()
            return self.analyze_mutual_fund(clean_q)
        else:
            clean_q = re.sub(r'(?i)\b(analyze|stock|share|company|industries|ltd|limited)\b', '', query).strip()
            resolved = tool_search_indian_symbol(clean_q)
            target = resolved.get("resolvedStockSymbol") or clean_q
            return self.analyze_stock(target)
